name: Cron Update

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:

    name: Trigger Netlify build
    runs-on: ubuntu-latest    
    steps:
    - name: Post to Netlify API
      run: curl -X POST -d {} https://api.netlify.com/build_hooks/5ddda91822f90a343e4cd84b
